### ISSUE TITLE
In safari not work

### ISSUE THREAD

**Issue by creativify** [ubenzer/sidenavjs#3]
In safari not work sidevanjs, not open!

**Comment by supercreators** [comment]
The problem is jquery! I cant fixed, I need help!

**Comment by ubenzer** [comment]
Hi creativify,

I can confirm that `sidenav` is working with the Safari 9.x series. Please note that I don't support older versions of any browser as this library is in pretty stages.

If you can provide more information about jQuery problem and/or Safari (preferably a demo to demonstrate the issue) I'd try to help.

Please open this issue if you can provide more information!
