### ISSUE TITLE
Sidenav doesn't close on location change (angular)

### ISSUE THREAD

**Issue by cata-libuy** [ubenzer/sidenavjs#4]
Hi

I just implemented your sidenav on angular.
It works very good inside one page, but if I click on a link of the menu (inside the sidenav), it remains open when I change the location.

I tried to access to the function isOpened(), but it seems that when I change the page (and controller), there´s no sidebar initialized yet, so I can´t close it.

**Comment by ubenzer** [comment]
Hi cata-libuy,

I recommend you to initialize `sidenav` in a global place. (Like a top level controller that never gets destructed on route changes). When you initialize `sidenav` using

```js
var sidenav = new Sidenav({
  content: document.getElementById("content"),
  sidenav: document.getElementById("sidenav"),
  backdrop: document.getElementById("backdrop")
});
```

You get a `sidenav` variable you should **never** lose access to this in your application's lifecycle. As `sidenav` is framework-free, there is no-way that `sidenav` automatically recognizes angular route change. But, on your top-level controller which you hold `sidenav` you can listen to location change events of Angular (such as [$locationCchangeSucces](https://docs.angularjs.org/api/ng/service/$location#$locationChangeSuccess) etc.) and call `sidenav.close()`.

Do not initialize `sidenav` on each page change, instead **keep** the first `sidenav` variable or you'll face a memory leak and possible some weird UI.

Also please note that, `sidenav` as it is now, doesn't offer a proper `cleanup` like `sidenav.destroy()`. So if you are planning to dynamically add/remove sidenav keep in mind.

Hope this helps.

Please reopen this issue if you need any help.
