### ISSUE TITLE
can't use this with react-native

### ISSUE THREAD

**Issue by abdallahbouhannache** [ubenzer/sidenavjs#44]
is this package only for react-js use or for react-native too ,
since i imported it and replaced all the components with appropriate ones from react-native but it showed me this error view config not found for name div? so i guess it is react js usage only .

![z](https://user-images.githubusercontent.com/29000485/76015804-0f619d80-5f1c-11ea-8db3-e85c09fde0a4.png)

**Comment by ubenzer** [comment]
Hi @abdallahbouhannache ,

This package is for `react-js` only. The `react-native` is not supported at this time.
