### ISSUE TITLE
Fixed menu for desktop

### ISSUE THREAD

**Issue by jmls** [ubenzer/sidenavjs#5]
If I am using this in a desktop, is there an option to make the sidebar permanently visible ?

**Comment by Codecors** [comment]
remove style **transform: translate3d(-380px, 0px, 0px);**  --> from id="sidenav" 
    margin-left: 350px; to sn-content

**Comment by ubenzer** [comment]
Hi @jmls This library is optimized for mobile use only. In my opinion, for desktop views, another component can be used. However, if you believe that this feature is useful can be implemented without in a generic way that works for everyone without crippling the performance, I would be happy to consider it.

Feel free to propose an api and/or an implementation plan for this.

As I retrigger the development of this library, I am aware that I reply to this after 2 years. Therefore, I will close this issue. Feel free to open a new one if you are still interested!

Cheers!
